### ISSUE TITLE
उदाहरणम् प्रदर्श्यताम्

### ISSUE THREAD

**Issue by vvasuki** [031323/v#2]
**य**था "रा**म**स्य भा**र्या** सी**ता** व**नं** ग**ता**" **इ**ति वा**क्य**स्य ध्व**निः** **क**थम् उत्पत्स्यत **इ**ति यन्त्रचाल**नं** वि**ना** जानीयात् **क**श्चित् कुतूह**ल**वान्।

**Comment by ujjvlh** [comment]
[1.wav.gz](https://github.com/031323/vackm/files/5011739/1.wav.gz)

[**अ**त्र](https://github.com/031323/vackm/commit/420c710eaef6730fb67f7537c3a5d6cae2196787) checkout कृ**त्वेदं** जनि**त**म्।

**Comment by ujjvlh** [comment]
README **प**रिवर्तिता।
